- name: Node Exporter Download
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v{{node-exporter_version}}/node_exporter-{{node-exporter_version}}.linux-amd64.tar.gz
    dest: "/opt"
    remote_src: yes

- name: Copy Node Exporter Service File
  ansible.builtin.template:
    src: node-exporter service
    dest: /etc/systemd/system/node-exporter.service

- name: Start node-exporter service
  ansible.builtin.systemd:
    name: node-exporter
    state: restarted
    enabled: yes
    demon-reload: yes
