- name: Node Exporter Download
  ansible.builtin.unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz"
    dest: "/opt"


- name: Copy Service
  ansible.builtin.template:
    src: node-exporter.service
    dest: /etc/systemd/system/node-exporter.service

- name: Restart Service
  ansible.builtin.systemd:
    name: node-exporter
    state: restarted
    enabled: yes
    daemon-reload: yes

